### PR TITLE
Start Migration from Travis CI

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This starts the migration from Travis CI to Github Actions. This allows us to view logs directly from Github and test on multiple operating systems.

### CODE REVIEW

**Review by R4356th — COMMENTED** [review]
What is the .prettierignore for?

**Comment by GrahamSH-LLK** [comment]
So that prettier doesn't glitch out trying to format the .github folder, which is off-limits for actions.

**Comment by R4356th** [comment]
Okay, great. Thank you very much. But should not we delete the .travis.yml file though?

**Comment by GrahamSH-LLK** [comment]
Yeah, I guess we should. ⬆️

**Pull request merged**
