### PR TITLE
Edit Button

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This is untested, although it does pass on PHP. It still needs a check to see if the value is either true or false, not something different.

### CODE REVIEW

**Review by R4356th — COMMENTED** [review]
This LGTM at first glance. I will test it locally soon.

**Comment by GrahamSH-LLK** [comment]
@R4356th Can you test this?

**Comment by R4356th** [comment]
I am very sorry for the delay. I will test this tomorrow.

**Comment by R4356th** [comment]
Never mind. I am reviewing this right now.

**Review by R4356th — APPROVED** [review]
It is good to go now. Thank you very much. :)

**Pull request merged**
