### PR TITLE
Add checks for PHP 8.x

### PR DESCRIPTION
**Pull request by R4356th**
MediaWiki may add support for it and Miraheze is planning to add it, too.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Looks good, but can you do .x like that?

**Comment by R4356th** [comment]
I think so as the checks are all green and details say that PHP 8.0 was used.

**Comment by R4356th** [comment]
Do you still have any concerns, @GrahamSH-LLK?

**Comment by GrahamSH-LLK** [comment]
Nope!

**Pull request merged**
